### ISSUE TITLE
Simplify default _pkgdown.yml

### ISSUE THREAD

**Issue by mvuorre** [CrumpLab/vertical#36]
This file will probably look difficult to beginners, so simplicity is best. How about we remove the following things:

```
pkgdown:
  as_is: true
```

```
  structure:
    left:
    - home
    - manuscript
    - articles
    - slides
    - posters
    - experiments
    - reference
    right: github
```

```
    - text: A link to Y
      href: another link
```

And put a link to https://pkgdown.r-lib.org/articles/pkgdown.html on the top of the file

?
